/// <autosync enabled="true" />
/// <reference path="vendor/jquery/dist/jquery.js"/>
/// <reference path="vendor/bootstrap/dist/js/bootstrap.js"/>
/// <reference path="vendor/toastr/toastr.js"/>
/// <reference path="vendor/raty/lib/jquery.raty.js"/>
/// <reference path="vendor/respond/dest/respond.src.js"/>
/// <reference path="vendor/angular/angular.js"/>
/// <reference path="vendor/angular-base64/angular-base64.js"/>
/// <reference path="vendor/angular-file-upload/dist/angular-file-upload.min.js"/>
/// <reference path="vendor/angucomplete-alt/dist/angucomplete-alt.min.js"/>
/// <reference path="vendor/angular-route/angular-route.js"/>
/// <reference path="vendor/angular-cookies/angular-cookies.js"/>
/// <reference path="vendor/angular-bootstrap/ui-bootstrap.js"/>
/// <reference path="vendor/angular-bootstrap/ui-bootstrap-tpls.js"/>
/// <reference path="vendor/tg-angular-validator/dist/angular-validator.js"/>
/// <reference path="vendor/raphael/raphael.js"/>
/// <reference path="vendor/morris.js/morris.js"/>
/// <reference path="vendor/underscore/underscore.js"/>
/// <reference path="vendor/angular-loading-bar/src/loading-bar.js"/>
/// <reference path="vendor/fancybox/source/jquery.fancybox.js"/>
/// <reference path="vendor/fancybox/source/jquery.fancybox.pack.js"/>
/// <reference path="vendor/fancybox/source/helpers/jquery.fancybox-media.js"/>
/// <reference path="spa/app.js" />
/// <reference path="spa/services/apiservice.js" />
/// <reference path="spa/services/notificationservice.js" />
/// <reference path="spa/movies/moviesctrl.js" />
/// <reference path="spa/movies/moviedetailsctrl.js" />
/// <reference path="spa/movies/movieaddctrl.js" />
/// <reference path="spa/movies/movieeditctrl.js" />
/// <reference path="spa/layout/custompager.directive.js" />
/// <reference path="spa/layout/sidebar.directive.js" />
/// <reference path="spa/layout/topbar.directive.js" />
/// <reference path="spa/directives/rating.directive.js" />
/// <reference path="spa/services/membershipservice.js" />
/// <reference path="spa/services/fileuploadservice.js" />
/// <reference path="spa/customers/customersctrl.js" />
/// <reference path="spa/customers/customersregctrl.js" />
/// <reference path="spa/directives/availablemovie.directive.js" />
/// <reference path="spa/home/rootctrl.js" />
/// <reference path="spa/home/indexctrl.js" />
/// <reference path="spa/rental/rentmoviectrl.js" />
/// <reference path="spa/rental/rentstatsctrl.js" />
/// <reference path="spa/customers/customereditctrl.js" />
/// <reference path="spa/account/loginctrl.js" />
/// <reference path="spa/account/registerctrl.js" />
/// <reference path="spa/modules/common.core.js" />
/// <reference path="spa/modules/common.ui.js" />